language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
  - "3.3"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y python-pyside
install:
  - pip install coveralls
  - pip install pypandoc
  - pip install pytest
  - pip install 'pytest-qt>=1.2.1'
  - pip install pytest-cov
  - pip install pytest-mock
  - python setup.py install
script: make test-single
after_success:
  coveralls
