language: python
python:
  - "2.7"
  - "3.4"
sudo: false
addons:
  apt:
    packages:
    - ghc
    - cabal-install
before_install:
  - cabal update
  - cabal install pandoc
  - export PATH=~/.cabal/bin:$PATH
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
  - pip install qtpy
  - pip install qtawesome
  - pip install coveralls
  - pip install 'pypandoc>=0.9.7'
  - pip install pandocfilters
  - pip install pytest
  - pip install 'pytest-qt>=1.2.1'
  - pip install pytest-cov
  - pip install pytest-mock
  - python setup.py install
script: make test-single
after_success:
  coveralls
