language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install coveralls
  - pip install pypandoc
  - pip install PySide
  - pip install pytest
  - pip install 'pytest-qt>=1.2.1'
  - pip install pytest-cov
  - pip install pytest-mock
  - python setup.py install
script: make test
after_success:
  coveralls
